from enum import Enum, auto

class EventType(str, Enum):
    # System events
    SYSTEM_STARTED = "SYSTEM_STARTED"
    SYSTEM_WARNING = "SYSTEM_WARNING"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SYSTEM_METRICS = "SYSTEM_METRICS"

    # Frame & Camera
    FRAME_PROCESSED = "FRAME_PROCESSED"
    CAMERA_CONNECTED = "CAMERA_CONNECTED"
    CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED"
    CAMERA_QUALITY_WARNING = "CAMERA_QUALITY_WARNING"

    # Detection & Pose
    PERSON_DETECTED = "PERSON_DETECTED"
    PERSON_LOST = "PERSON_LOST"
    OBJECT_DETECTED = "OBJECT_DETECTED"
    OBJECT_MOVED = "OBJECT_MOVED"
    OBJECT_GRASPED = "OBJECT_GRASPED"
    OBJECT_RELEASED = "OBJECT_RELEASED"
    OBJECT_PLACED = "OBJECT_PLACED"
    OBJECT_LOST = "OBJECT_LOST"
    POSE_UPDATED = "POSE_UPDATED"
    HAND_UPDATED = "HAND_UPDATED"
    INTERACTION_UPDATED = "INTERACTION_UPDATED"

    # Activity
    ACTIVITY_STARTED = "ACTIVITY_STARTED"
    ACTIVITY_CHANGED = "ACTIVITY_CHANGED"
    ACTIVITY_COMPLETED = "ACTIVITY_COMPLETED"

    # Sequence & Steps
    STEP_STARTED = "STEP_STARTED"
    STEP_PROGRESS = "STEP_PROGRESS"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_SKIPPED = "STEP_SKIPPED"
    STEP_FAILED = "STEP_FAILED"

    # Errors & Recovery
    ERROR_DETECTED = "ERROR_DETECTED"
    ERROR_CLEARED = "ERROR_CLEARED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"

    # Alerts & Guidance
    VOICE_ALERT = "VOICE_ALERT"
    NEXT_STEP_CHANGED = "NEXT_STEP_CHANGED"

    # Experiment Control
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    EXPERIMENT_PAUSED = "EXPERIMENT_PAUSED"
    EXPERIMENT_RESUMED = "EXPERIMENT_RESUMED"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"
    EXPERIMENT_ABORTED = "EXPERIMENT_ABORTED"

class SafetyState(str, Enum):
    CONFIRMED = "CONFIRMED"
    UNCERTAIN = "UNCERTAIN"
    ERROR = "ERROR"

class InteractionState(str, Enum):
    FAR = "FAR"
    APPROACHING = "APPROACHING"
    NEAR = "NEAR"
    CONTACT = "CONTACT"
    GRASPING = "GRASPING"
    MOVING = "MOVING"
    RELEASING = "RELEASING"
    PLACED = "PLACED"

class ActivityType(str, Enum):
    IDLE = "IDLE"
    REACH = "REACH"
    OPEN_CONTAINER = "OPEN_CONTAINER"
    IDENTIFY_OBJECT = "IDENTIFY_OBJECT"
    GRASP = "GRASP"
    MOVE = "MOVE"
    PLACE = "PLACE"
    RELEASE = "RELEASE"
    COMPLETE = "COMPLETE"
    ERROR = "ERROR"

class ErrorType(str, Enum):
    STEP_SKIPPED = "STEP_SKIPPED"
    OUT_OF_SEQUENCE = "OUT_OF_SEQUENCE"
    WRONG_OBJECT = "WRONG_OBJECT"
    WRONG_ACTION = "WRONG_ACTION"
    STEP_TIMEOUT = "STEP_TIMEOUT"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    OBJECT_LOST = "OBJECT_LOST"
    PERSON_LOST = "PERSON_LOST"
    CAMERA_FAILURE = "CAMERA_FAILURE"
    MODEL_FAILURE = "MODEL_FAILURE"
